import React from "react";
import { useContext } from "react";
import { ThemeContext } from "../components/Theme/ThemeContext";
import HeaderPage from "../components/HeaderPages";

const ComparativoPage = () => {
  const { theme } = useContext(ThemeContext);

  let S = {
    root: { display: "flex", minHeight: "100vh", background: theme.bg },
    sidebar: {
      width: 220,
      background: theme.surface,
      borderRight: `1px solid ${theme.border}`,
      display: "flex",
      flexDirection: "column",
      padding: "24px 14px",
      position: "sticky",
      top: 0,
      height: "100vh",
    },
    brand: { display: "flex", alignItems: "center", gap: 9, marginBottom: 32 },
    dot: {
      width: 8,
      height: 8,
      background: theme.teal,
      borderRadius: "50%",
      boxShadow: `0 0 8px ${theme.teal}`,
    },
    brandTxt: {
      fontFamily: "'Bricolage Grotesque',sans-serif",
      fontSize: 17,
      fontWeight: 800,
      color: theme.text,
      letterSpacing: 2,
    },
    nav: { display: "flex", flexDirection: "column", gap: 3, flex: 1 },
    navBtn: {
      display: "flex",
      alignItems: "center",
      gap: 9,
      padding: "9px 11px",
      background: "transparent",
      border: "none",
      borderRadius: 9,
      color: theme.muted,
      fontSize: 13,
      fontFamily: "'Mulish',sans-serif",
      position: "relative",
    },
    navOn: { color: theme.text, background: theme.border },
    navBar: {
      position: "absolute",
      right: 0,
      top: "50%",
      transform: "translateY(-50%)",
      width: 3,
      height: 16,
      background: theme.teal,
      borderRadius: "2px 0 0 2px",
      boxShadow: `0 0 8px ${theme.teal}`,
    },
    sideFooter: {
      paddingTop: 16,
      borderTop: `1px solid ${theme.border}`,
      display: "flex",
      flexDirection: "column",
      gap: 8,
    },
    sideChip: { background: theme.border, borderRadius: 10, padding: "10px 12px" },
    sideChipLbl: {
      display: "block",
      color: theme.muted,
      fontSize: 10,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: 1.5,
      marginBottom: 4,
    },
    sideChipVal: {
      display: "block",
      fontFamily: "'JetBrains Mono',monospace",
      fontSize: 18,
      fontWeight: 700,
    },
    sidebarLogoutBtn: {
      marginTop: 6,
      height: 36,
      borderRadius: 10,
      border: `1px solid ${theme.border2}`,
      background: theme.border,
      color: theme.text,
      fontSize: 12,
      fontWeight: 700,
      fontFamily: "'Mulish',sans-serif",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    topBar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "14px 24px",
      borderBottom: `1px solid ${theme.border}`,
      background: theme.surface,
      position: "sticky",
      top: 0,
      zIndex: 5,
    },
    topBarTitle: {
      color: theme.text,
      fontFamily: "'Bricolage Grotesque',sans-serif",
      fontWeight: 700,
      fontSize: 18,
      letterSpacing: 0.5,
    },
    profileWrap: { display: "flex", alignItems: "center", gap: 10 },
    profileEmail: {
      color: theme.muted,
      fontSize: 12,
      fontWeight: 600,
      maxWidth: 220,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    profileBtn: {
      width: 34,
      height: 34,
      borderRadius: "50%",
      border: `1px solid ${theme.border2}`,
      background: theme.border,
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
    },
    main: { flex: 1, overflow: "auto" },
    page: { padding: "36px 42px", maxWidth: 1200, margin: "0 auto" },
    pageHead: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-end",
      marginBottom: 28,
    },
    eyebrow: {
      color: theme.teal,
      fontSize: 11,
      fontWeight: 700,
      letterSpacing: 3,
      textTransform: "uppercase",
      marginBottom: 4,
    },
    pageTitle: {
      fontFamily: "'Bricolage Grotesque',sans-serif",
      fontSize: 32,
      fontWeight: 800,
      color: theme.text,
    },
    dateBadge: {
      color: theme.muted,
      fontSize: 12,
      padding: "7px 14px",
      background: theme.surface,
      borderRadius: 8,
      border: `1px solid ${theme.border}`,
    },
    grid4: {
      display: "grid",
      gridTemplateColumns: "repeat(4,1fr)",
      gap: 14,
      marginBottom: 20,
    },
    kpi: {
      background: theme.surface,
      border: `1px solid ${theme.border}`,
      borderRadius: 14,
      padding: "16px 18px",
      display: "flex",
      flexDirection: "column",
    },
    row: { display: "flex", gap: 16 },
    card: {
      background: theme.surface,
      border: `1px solid ${theme.border}`,
      borderRadius: 14,
      padding: "18px 20px",
    },
    listRow: {
      display: "flex",
      alignItems: "center",
      gap: 14,
      padding: "12px 16px",
      background: theme.surface,
      border: `1px solid ${theme.border}`,
      borderRadius: 12,
      cursor: "pointer",
      transition: "border-color .15s",
    },
    listRowOn: { borderColor: theme.teal + "55", background: theme.surface },
    listName: { color: theme.text, fontWeight: 600, fontSize: 14 },
    rowActs: { display: "flex", gap: 5 },
    quickStats: {
      display: "flex",
      flexDirection: "column",
      gap: 7,
      marginTop: 14,
      paddingTop: 14,
      borderTop: `1px solid ${theme.border}`,
    },
    quickRow: { display: "flex", justifyContent: "space-between" },
    ingGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fill,minmax(230px,1fr))",
      gap: 14,
    },
    ingCard: {
      background: theme.surface,
      border: `1px solid ${theme.border}`,
      borderRadius: 13,
      padding: 16,
    },
    priceIn: {
      background: theme.bg,
      border: `1px solid ${theme.teal}`,
      borderRadius: 7,
      padding: "4px 8px",
      fontSize: 16,
      color: theme.teal,
      fontFamily: "'JetBrains Mono',monospace",
      width: 120,
    },
    opRow: {
      display: "flex",
      alignItems: "center",
      gap: 14,
      padding: "11px 14px",
      background: theme.surface,
      borderRadius: 10,
      border: `1px solid ${theme.border}`,
    },
    search: {
      width: "100%",
      padding: "9px 14px",
      background: theme.bg,
      border: `1px solid ${theme.border}`,
      borderRadius: 10,
      fontSize: 13,
      color: theme.text,
      marginBottom: 12,
      fontFamily: "'Mulish',sans-serif",
    },
    toggleBtn: {
      background: "transparent",
      border: `1px solid ${theme.border}`,
      borderRadius: 8,
      padding: "7px 16px",
      color: theme.muted,
      fontSize: 13,
      fontFamily: "'Mulish',sans-serif",
    },
    toggleOn: { background: theme.teal + "22", borderColor: theme.teal, color: theme.teal },
    overlay: {
      position: "fixed",
      inset: 0,
      background: "rgba(0,0,0,.82)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 100,
      padding: 20,
    },
    modal: {
      background: theme.surface,
      border: `1px solid ${theme.border2}`,
      borderRadius: 18,
      width: "100%",
      maxHeight: "90vh",
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
      boxShadow: "0 24px 80px rgba(0,0,0,.6)",
    },
    modalHead: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "18px 22px",
      borderBottom: `1px solid ${theme.border}`,
    },
    modalTitle: {
      fontFamily: "'Bricolage Grotesque',sans-serif",
      fontSize: 20,
      fontWeight: 700,
      color: theme.text,
    },
    closeBtn: {
      background: theme.border,
      border: "none",
      borderRadius: 7,
      width: 28,
      height: 28,
      color: theme.muted,
      fontSize: 13,
    },
    modalBody: { padding: "20px 22px", overflow: "auto", flex: 1 },
    inp: {
      width: "100%",
      padding: "9px 12px",
      background: theme.bg,
      border: `1px solid ${theme.border}`,
      borderRadius: 8,
      color: theme.text,
      fontSize: 13,
      fontFamily: "'Mulish',sans-serif",
    },
    btnPrimary: {
      background: theme.teal,
      color: theme.bg,
      padding: "9px 20px",
      borderRadius: 9,
      border: "none",
      fontWeight: 700,
      fontSize: 13,
      fontFamily: "'Mulish',sans-serif",
    },
    btnOutline: {
      background: "transparent",
      color: theme.muted,
      padding: "9px 20px",
      borderRadius: 9,
      border: `1px solid ${theme.border}`,
      fontWeight: 600,
      fontSize: 13,
      fontFamily: "'Mulish',sans-serif",
    },
    toast: {
      position: "fixed",
      bottom: 22,
      right: 22,
      background: theme.surface,
      border: "1px solid",
      padding: "10px 18px",
      borderRadius: 10,
      fontWeight: 600,
      zIndex: 200,
      fontSize: 12,
      fontFamily: "'JetBrains Mono',monospace",
    },
    th: {
      padding: "8px 12px",
      textAlign: "left",
      color: theme.muted,
      fontSize: 10,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: 1,
      borderBottom: `1px solid ${theme.border}`,
    },
    td: { padding: "9px 12px", color: theme.text, fontSize: 13 },
    empty: {
      color: theme.muted,
      textAlign: "center",
      padding: "48px 20px",
      fontSize: 14,
    },
  };


  return (
    <div
      style={{
        backgroundColor: theme.bg,
        color: theme.text,
        height: "100vh",
        display: "flex",
        justifyContent: "center",
      }}
    >
      <HeaderPage
        eyebrow="Análise"
        title="Comparativo de Custo no Tempo"
      />
    </div>
  );
};

export default ComparativoPage;
